/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package familyTree;

import familyTree.util.MyTableModel;
import familyTree.util.IntOnlyFilter;
import familyTree.util.RelationShipModel;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javafx.scene.control.RadioButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;

/**
 *
 * @author cuho1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Vector<Human> humanList = new Vector<>();
    int currentMaxID = 0;
    Human currentHuman = null;
    Calendar bornday = Calendar.getInstance();
    Calendar deathday= Calendar.getInstance();
    Human curFather, curMother, curSpouse;
    Vector<Human> humanChildrend =  new Vector<>();
    Vector<Human> humanListsrc = new Vector<Human>();
    RelationShipModel source, children,current;
    Vector<Human> humanrela = new Vector<Human>();
    MyTableModel model ;
    public Main() {
        initComponents();
        loadData();
        iniTable();
        initShowfield();
        initHumanrela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        dialog_childrend = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        source_tb = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        children_tb = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        dialog_father = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        father_tb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        dialog_mother = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        mother_tb = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        dialog_spouse = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        spouse_tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonNew = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_deathyear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_bornday = new javax.swing.JComboBox();
        cb_bornmonth = new javax.swing.JComboBox();
        tf_bornyear = new javax.swing.JTextField();
        cb_deathday = new javax.swing.JComboBox();
        cb_deathmonth = new javax.swing.JComboBox();
        jButtonFather = new javax.swing.JButton();
        jButtonMother = new javax.swing.JButton();
        jButtonSpouse = new javax.swing.JButton();
        jButtonChildrend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBiography = new javax.swing.JTextArea();
        jButtonDelete = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        source_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(source_tb);

        children_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(children_tb);

        btn_add.setText(">>");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_remove.setText("<<");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_childrendLayout = new javax.swing.GroupLayout(dialog_childrend.getContentPane());
        dialog_childrend.getContentPane().setLayout(dialog_childrendLayout);
        dialog_childrendLayout.setHorizontalGroup(
            dialog_childrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_childrendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_childrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialog_childrendLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_childrendLayout.setVerticalGroup(
            dialog_childrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_childrendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_childrendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(dialog_childrendLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_remove)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        father_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(father_tb);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_fatherLayout = new javax.swing.GroupLayout(dialog_father.getContentPane());
        dialog_father.getContentPane().setLayout(dialog_fatherLayout);
        dialog_fatherLayout.setHorizontalGroup(
            dialog_fatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_fatherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialog_fatherLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        dialog_fatherLayout.setVerticalGroup(
            dialog_fatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_fatherLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mother_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(mother_tb);

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_motherLayout = new javax.swing.GroupLayout(dialog_mother.getContentPane());
        dialog_mother.getContentPane().setLayout(dialog_motherLayout);
        dialog_motherLayout.setHorizontalGroup(
            dialog_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_motherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_motherLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(162, 162, 162))
        );
        dialog_motherLayout.setVerticalGroup(
            dialog_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_motherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spouse_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(spouse_tb);

        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_spouseLayout = new javax.swing.GroupLayout(dialog_spouse.getContentPane());
        dialog_spouse.getContentPane().setLayout(dialog_spouseLayout);
        dialog_spouseLayout.setHorizontalGroup(
            dialog_spouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_spouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_spouseLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(163, 163, 163))
        );
        dialog_spouseLayout.setVerticalGroup(
            dialog_spouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_spouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSearch)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setText("Avatar");

        jLabel3.setText("Name");

        jLabel2.setText("ID");

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setText("Male");

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setText("Female");

        jLabel4.setText("Born");

        jLabel5.setText("Death");

        cb_bornday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_bornday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_borndayActionPerformed(evt);
            }
        });

        cb_bornmonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_bornmonthItemStateChanged(evt);
            }
        });

        tf_bornyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bornyearActionPerformed(evt);
            }
        });
        tf_bornyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_bornyearKeyTyped(evt);
            }
        });

        cb_deathday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_deathmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldName)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_bornday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_deathday, 0, 1, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_bornmonth, 0, 54, Short.MAX_VALUE)
                            .addComponent(cb_deathmonth, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_bornyear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_deathyear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_bornday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bornmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_bornyear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_deathyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_deathday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_deathmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jTextFieldID});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldName, tf_deathyear});

        jButtonFather.setText("Father");
        jButtonFather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFatherActionPerformed(evt);
            }
        });

        jButtonMother.setText("Mother");
        jButtonMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotherActionPerformed(evt);
            }
        });

        jButtonSpouse.setText("Spouse");
        jButtonSpouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpouseActionPerformed(evt);
            }
        });

        jButtonChildrend.setText("Childrend");
        jButtonChildrend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChildrendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFather, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonMother)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSpouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonChildrend)
                        .addContainerGap())))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonFather, jButtonMother});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMother)
                            .addComponent(jButtonFather))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSpouse)
                            .addComponent(jButtonChildrend))
                        .addContainerGap())))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonFather, jButtonMother});

        jTextAreaBiography.setColumns(20);
        jTextAreaBiography.setRows(5);
        jTextAreaBiography.setBorder(javax.swing.BorderFactory.createTitledBorder("Biography"));
        jScrollPane1.setViewportView(jTextAreaBiography);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        save();
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void cb_borndayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_borndayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_borndayActionPerformed

    private void tf_bornyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bornyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bornyearActionPerformed

    private void cb_bornmonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_bornmonthItemStateChanged
        // TODO add your handling code here:
        Date x = bornday.getTime();
        x.setMonth(cb_bornmonth.getSelectedIndex());
        bornday.setTime(x);
        buildDaysList(bornday, cb_bornday, cb_bornmonth);
    }//GEN-LAST:event_cb_bornmonthItemStateChanged

    private void tf_bornyearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bornyearKeyTyped
        // TODO add your handling code here:
        Date x = bornday.getTime();
        x.setYear(Integer.parseInt(tf_bornyear.getText()));
        bornday.setTime(x);
        
        
    }//GEN-LAST:event_tf_bornyearKeyTyped

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
        addNew();
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonChildrendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChildrendActionPerformed
        // TODO add your handling code here:
        humanListsrc.clear();
        for (Human a : humanList){
            if ((a.getBorn().after(bornday.getTime()))&&
                    (!humanChildrend.contains(a))) humanListsrc.add(a);
        }
        source = new RelationShipModel(humanListsrc, currentHuman);
        source_tb.setModel(source);
        children = new RelationShipModel(humanChildrend, currentHuman);
        children_tb.setModel(children);
        dialog_childrend.setSize(595, 220);
        dialog_childrend.setLocationRelativeTo(this);
        dialog_childrend.setVisible(true);
        
    }//GEN-LAST:event_jButtonChildrendActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        int choose = source_tb.getSelectedRow();
        humanChildrend.add(humanListsrc.elementAt(choose));
        humanListsrc.remove(choose);
        source.fireTableDataChanged();
        children.fireTableDataChanged();
        
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        dialog_childrend.setVisible(false);
        initHumanrela();
        
    }//GEN-LAST:event_btn_okActionPerformed

    private void jButtonFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFatherActionPerformed
        // TODO add your handling code here:
        humanListsrc.clear();
        for (Human a : humanList){
            if ((a.getBorn().before(bornday.getTime()))&&(a.isMale()))
                humanListsrc.add(a);
        }
        source = new RelationShipModel(humanListsrc, currentHuman);
        father_tb.setModel(source);
        dialog_father.setSize(595, 220);
        dialog_father.setLocationRelativeTo(this);
        dialog_father.setVisible(true);
    }//GEN-LAST:event_jButtonFatherActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int choose = children_tb.getSelectedRow();
        humanListsrc.add(humanChildrend.elementAt(choose));
        humanChildrend.remove(choose);
        source.fireTableDataChanged();
        children.fireTableDataChanged();
    }//GEN-LAST:event_btn_removeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (father_tb.getSelectedRow()==-1) curFather=null;
        else curFather=humanListsrc.elementAt(father_tb.getSelectedRow());

        dialog_father.setVisible(false);
        initHumanrela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotherActionPerformed
        // TODO add your handling code here:
        humanListsrc.clear();
        for (Human a : humanList){
            if ((a.getBorn().before(bornday.getTime()))&&(!a.isMale()))
                humanListsrc.add(a);
        }
        source = new RelationShipModel(humanListsrc, currentHuman);
        mother_tb.setModel(source);
        dialog_mother.setSize(595, 220);
        dialog_mother.setLocationRelativeTo(this);
        dialog_mother.setVisible(true);
    }//GEN-LAST:event_jButtonMotherActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (mother_tb.getSelectedRow()==-1) curMother=null;
        else curMother=humanListsrc.elementAt(mother_tb.getSelectedRow());

        dialog_mother.setVisible(false);
        initHumanrela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSpouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpouseActionPerformed
        // TODO add your handling code here:
        humanListsrc.clear();
        for (Human a : humanList){
            if (jRadioButton1.isSelected()^(!a.isMale())) humanListsrc.add(a);
        }
        source = new RelationShipModel(humanListsrc, currentHuman);
        spouse_tb.setModel(source);
        dialog_spouse.setSize(595, 220);
        dialog_spouse.setLocationRelativeTo(this);
        dialog_spouse.setVisible(true);
    }//GEN-LAST:event_jButtonSpouseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (spouse_tb.getSelectedRow()==-1) curSpouse=null;
        else curSpouse=humanListsrc.elementAt(spouse_tb.getSelectedRow());

        dialog_spouse.setVisible(false);
        initHumanrela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>c

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_remove;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox cb_bornday;
    private javax.swing.JComboBox cb_bornmonth;
    private javax.swing.JComboBox cb_deathday;
    private javax.swing.JComboBox cb_deathmonth;
    private javax.swing.JTable children_tb;
    private javax.swing.JDialog dialog_childrend;
    private javax.swing.JDialog dialog_father;
    private javax.swing.JDialog dialog_mother;
    private javax.swing.JDialog dialog_spouse;
    private javax.swing.JTable father_tb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonChildrend;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFather;
    private javax.swing.JButton jButtonMother;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSpouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaBiography;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTable mother_tb;
    private javax.swing.JTable source_tb;
    private javax.swing.JTable spouse_tb;
    private javax.swing.JTextField tf_bornyear;
    private javax.swing.JTextField tf_deathyear;
    // End of variables declaration//GEN-END:variables

    private void iniTable() {
        model = new MyTableModel(humanList);
        jTable.setModel(model);
        jTable.setRowSelectionAllowed(true);
        
    }

    private void initShowfield() {
        jTextFieldID.setText(String.valueOf(currentMaxID+1));
        jTextFieldName.setText(""); 
        jTextAreaBiography.setText("");
        //Date date = Calendar.getInstance().getTime();
        
        PlainDocument doc = (PlainDocument) tf_bornyear.getDocument();
        doc.setDocumentFilter(new IntOnlyFilter());
        tf_bornyear.setText(""+bornday.get(Calendar.YEAR)); 
        buildMonthsList(cb_bornmonth);
        cb_bornmonth.setSelectedIndex(bornday.get(Calendar.MONTH));
        buildDaysList(bornday, cb_bornday, cb_bornmonth);
        cb_bornday.setSelectedIndex(bornday.get(Calendar.DATE)-1);
        
        
        PlainDocument doc2 = (PlainDocument) tf_deathyear.getDocument();
        doc2.setDocumentFilter(new IntOnlyFilter());
        tf_deathyear.setText(""+deathday.get(Calendar.YEAR)); 
        buildMonthsList(cb_deathmonth);
        cb_deathmonth.setSelectedIndex(deathday.get(Calendar.MONTH));
        buildDaysList(deathday, cb_deathday, cb_deathmonth);
        cb_deathday.setSelectedIndex(deathday.get(Calendar.DATE)-1);
        
        
        //jComboBoxChild.setModel(null);
        currentHuman=null;
        
        initHumanrela();
    }
    
    private void buildMonthsList(JComboBox monthsList) {

        monthsList.removeAllItems();
        for (int monthCount = 0; monthCount < 12; monthCount++)
            monthsList.addItem(monthCount+1);
    }
   
    private void buildDaysList(Calendar dateIn, JComboBox daysList, JComboBox monthsList) {

        daysList.removeAllItems();
        dateIn.set(Calendar.MONTH, monthsList.getSelectedIndex());
        int lastDay = bornday.getActualMaximum(Calendar.DAY_OF_MONTH);

        for (int dayCount = 1; dayCount <= lastDay; dayCount++)
            daysList.addItem(Integer.toString(dayCount));
    }
    
    
    
    
    
    private void loadData() {
        File file = new File("humanData.dat");
        if(!file.exists()){
            JOptionPane.showMessageDialog(this, "Không tìm thấy file \"humanData.dat\"");
            return;
        }
        try {
            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);
            humanList =  (Vector<Human>) ois.readObject();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy file \"humanData.dat\"");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi khi đọc file \"humanData.dat\"");
        }
    }
    
    private boolean saveData(){
        File file = new File("humanData.dat");
        try {
            ObjectOutputStream oos;
            try (FileOutputStream fos = new FileOutputStream(file)) {
                oos = new ObjectOutputStream(fos);
                oos.writeObject(humanList);
            }
            oos.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi khi ghi file \"humanData.dat\"");
            return false;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi khi ghi file \"humanData.dat\"");
            return false;
        }
        return true;
    }
    
    private void show(Human human){
        currentHuman = human;
        jTextFieldID.setText(human.getID());
        jTextFieldName.setText(human.getName()); 
        jTextAreaBiography.setText("");
        bornday.setTime(human.born);
        buildMonthsList(cb_bornmonth);
        cb_bornmonth.setSelectedIndex(bornday.get(Calendar.MONTH));
        buildDaysList(bornday, cb_bornday, cb_bornmonth);
        cb_bornday.setSelectedIndex(bornday.get(Calendar.DATE));
        
        deathday.setTime(human.death);
        buildMonthsList(cb_deathmonth);
        cb_deathmonth.setSelectedIndex(deathday.get(Calendar.MONTH));
        buildDaysList(deathday, cb_deathday, cb_deathmonth);
        cb_deathday.setSelectedIndex(deathday.get(Calendar.DATE));
        
        
    }
    
    private void addNew(){
        //currentMaxID++;
        jTextFieldID.setText(String.valueOf(currentMaxID+1));
        jTextFieldName.setText(""); 
        jTextAreaBiography.setText("");
        bornday = Calendar.getInstance();
        tf_bornyear.setText(""+bornday.get(Calendar.YEAR)); 
        buildMonthsList(cb_bornmonth);
        cb_bornmonth.setSelectedIndex(bornday.get(Calendar.MONTH));
        buildDaysList(bornday, cb_bornday, cb_bornmonth);
        cb_bornday.setSelectedIndex(bornday.get(Calendar.DATE));
        
        deathday= Calendar.getInstance();
        tf_deathyear.setText(""+deathday.get(Calendar.YEAR)); 
        buildMonthsList(cb_deathmonth);
        cb_deathmonth.setSelectedIndex(deathday.get(Calendar.MONTH));
        buildDaysList(deathday, cb_deathday, cb_deathmonth);
        cb_deathday.setSelectedIndex(deathday.get(Calendar.DATE)-1);
        
        
        currentHuman=null;
    }
    
    private void save(){
        if (currentHuman==null){
            currentHuman = new Human();
            currentHuman.setBorn(bornday.getTime());
            currentHuman.setDeath(null);
            currentHuman.setFather(curFather);
            currentHuman.setMother(curMother);
            currentHuman.setSpouse(curSpouse);
            currentHuman.setName(jTextFieldName.getText());
            currentHuman.setID(jTextFieldID.getText());
            currentHuman.setChildrenList(humanChildrend);
            currentHuman.setBiography(jTextAreaBiography.getText());
            currentHuman.setMale(jRadioButton1.isSelected());
            humanList.add(currentHuman);
            model.fireTableDataChanged();
           
        }
        else {
            currentHuman = new Human();
            currentHuman.setBorn(bornday.getTime());
            currentHuman.setDeath(null);
            currentHuman.setFather(curFather);
            currentHuman.setMother(curMother);
            currentHuman.setSpouse(curSpouse);
            currentHuman.setName(jTextFieldName.getText());
            currentHuman.setID(jTextFieldID.getText());
            currentHuman.setChildrenList(humanChildrend);
            currentHuman.setBiography(jTextAreaBiography.getText());
            currentHuman.setMale(jRadioButton1.isSelected());
            for (Human i:humanList){
                if (i.getID().compareTo(currentHuman.getID())==0){
                    humanList.remove(i);
                    humanList.add(currentHuman);
                }
            }
            model.fireTableDataChanged();
        }
    }

    private void initHumanrela() {
        
        humanrela.clear();
        current = new RelationShipModel(humanrela, currentHuman);
        //jTable1.setModel(current);
        for (Human i: humanChildrend){
            humanrela.add(i);
        }
        humanrela.add(curFather);
        humanrela.add(curMother);
        humanrela.add(curSpouse);
        current.fireTableDataChanged();
    }

    private void delete() {
        if (currentHuman==null){
            addNew();
        }
        else{
            currentHuman = new Human();
            currentHuman.setBorn(bornday.getTime());
            currentHuman.setDeath(null);
            currentHuman.setFather(curFather);
            currentHuman.setMother(curMother);
            currentHuman.setSpouse(curSpouse);
            currentHuman.setName(jTextFieldName.getText());
            currentHuman.setID(jTextFieldID.getText());
            currentHuman.setChildrenList(humanChildrend);
            currentHuman.setBiography(jTextAreaBiography.getText());
            currentHuman.setMale(jRadioButton1.isSelected());
            for (Human i:humanList){
                if (i.getID().compareTo(currentHuman.getID())==0){
                    humanList.remove(i);
                }
            }
            model.fireTableDataChanged();
        }
    }
    
    
}
